name: Testing stuff

on:
  push:
    branches:
      - dev

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: commit message
        if: ${{!contains(github.event.head_commit.message, '#skip')}}
        run: |
          echo 'bump'